### ISSUE TITLE
关于代码的运行结果

### ISSUE THREAD

**Issue by Bhongcheng** [JianXu95/FedPAC#3]
老哥，我还想向你请教一下。
为什么使用FedPAC时，ACC为什么先高后低呢

我理解像Fedavg那样经过本地训练后，本地测试效果应该更好啊

谢谢！！！！

**Comment by JianXu95** [comment]
啊？啥先高后低，接近收敛后本地训练不可能更好吧，因为训练过程本地所以参数都更新，但肯定global的feature extractor好，local 数据少训几个epoch只会过拟合，最终本地微调的话微调classifier head就行了。code中跟踪了本地训练前后的acc两个指标，一开始肯定acc2比较好，之后acc1应该接近acc2并达到差不多。可以在最后训练结束后再加一个本地classifier head微调步骤。发自我的 iPhone在 2023年5月14日，06:47，鲍鸿丞 ***@***.***> 写道：﻿
老哥，我还想向你请教一下。
为什么使用FedPAC时，ACC为什么先高后低呢
我理解像Fedavg那样经过本地训练后，本地测试效果应该更好啊
谢谢！！！！

**Comment by Bhongcheng** [comment]
对不起，昨天走的有点急，问题没有描述清楚，感谢老哥的回复。

我拿cifar10 num20做对比，这是FedAvg的最后一轮结果：
---- Global Communication Round : 200 ----
====================================
Train Loss: 0.6256585150957108, 0.21839438807219266
Local Accuracy on Local Data: 69.66666666666666%, 76.61666666666666%    

采用FedAvg时，acc2比acc1高很多（我理解acc2对应论文Table1中的FedAvg-FT，acc1对应FedAvg）。采用FedAvg时本地训练后同样会过拟合本地数据，但是在评价个性化准确率（即与本地训练集同分布的测试集的准确率）时，过拟合一定程度上是不是也会增加本地准确率呢？


然后这是FedPAC的最后一轮结果：
---- Global Communication Round : 200 ----
====================================
(1) Agg Weights of Classifier Head
[0.512819734647697, 0.0, 0.0, 0.0, 0.0, 0.1578348916110203, 0.0, 0.0, 0.0, 0.0, 0.1591713513548719, 0.0, 0.0, 0.0, 0.0, 0.17017402238641083, 0.0, 0.0, 0.0, 0.0] 

Train Loss: 0.3127198511268943, 0.3829281235734622
Local Accuracy on Local Data: 81.10000000000001%,  78.69999999999999%

可以看到，采用FedPAC时现象与FedAvg相反。如老哥所说“global的feature extractor好，local数据少训练几个epoch只会过拟合”，可是这样的话为什么FedAvg经过本地训练过拟合后效果更好，而FedPAC则与之相反呢？莫非是FedPAC本地训练时将分类器固定住的原因？

我要是有哪个地方理解错了，恳请老哥指定迷津呀！

谢谢老哥！！！！！！

**Comment by JianXu95** [comment]
啊这，因为fedavg的classifier head是global的classifier，肯定不如个性化的classifier好，本地训练时classifier也会拟合本地的分布（可能一个epoch就够好了），自然效果就会变好，但是训练太多个epoch之时，feature extractor就受到影响了发自我的 iPhone在 2023年5月14日，19:03，鲍鸿丞 ***@***.***> 写道：﻿
我拿cifar10 num20做对比，这是FedAvg的最后一轮结果

---- Global Communication Round : 200 ----
Train Loss: 0.6256585150957108, 0.21839438807219266
Local Accuracy on Local Data: 69.66666666666666%, 76.61666666666666%
采用FedAvg时，acc2比acc1高很多（我理解acc2对应论文Table1中的FedAvg-FT，acc1对应FedAvg）。采用FedAvg时本地训练后同样会过拟合本地数据，但是在评价个性化准确率（即与本地训练集同分布的测试集的准确率）时，过拟合一定程度上是不是也会增加本地准确率呢？


然后这是FedPAC的最后一轮结果

---- Global Communication Round : 200 ----
(1) Agg Weights of Classifier Head
[0.512819734647697, 0.0, 0.0, 0.0, 0.0, 0.1578348916110203, 0.0, 0.0, 0.0, 0.0, 0.1591713513548719, 0.0, 0.0, 0.0, 0.0, 0.17017402238641083, 0.0, 0.0, 0.0, 0.0]
Train Loss: 0.3127198511268943, 0.3829281235734622
Local Accuracy on Local Data: 81.10000000000001%,  78.69999999999999%
可以看到，采用FedPAC时现象与FedAvg相反。如老哥所说“global的feature extractor好，local数据少训练几个epoch只会过拟合”，可是这样的话为什么FedAvg经过本地训练过拟合后效果更好，而FedPAC则与之相反呢？莫非是FedPAC本地训练时将分类器固定住的原因？
我要是有哪个地方理解错了，恳请老哥指定迷津呀！

谢谢老哥！！！！！！

**Comment by Bhongcheng** [comment]
谢谢老哥
